- name: Add Jetstack repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install cert-manager
  kubernetes.core.helm:
    release_name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: 1.13.1
    create_namespace: true
    release_namespace: cert-manager
    wait: true
    values:
      installCRDs: true
